version: "3.9"

services:
  client:
    build:
      context: ./client
    ports:
      - "3000:3000"
  question:
    build:
      context: ./question-service
    ports:
      - "8888:8888"
    environment:
      - MONGODB_URL=mongodb://mongo
    depends_on:
      - mongo
  mongo:
    image: mongo:6
    ports:
      - 27017:27017
