version: "3.9"

services:
  client:
    build:
      context: ./client
    ports:
      - "3000:3000"
    environment:
      - QUESTIONS_API_URL=http://34.121.234.55:8888/questions
      - USER_API_URL=http://34.121.234.55:5100/user
    depends_on:
      - question
      - user
      - matching
      - collaboration

  question:
    build:
      context: ./question-service
    ports:
      - "8888:8888"
    environment:
      - CLIENT_URL=http://34.121.234.55:3000
      - MATCHING_URL=http://34.121.234.55:8080
      - SUPABASE_URL=https://iwxacjmydxiforzrvurs.supabase.co
      - SUPABASE_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml3eGFjam15ZHhpZm9yenJ2dXJzIiwicm9sZSI6ImFub24iLCJpYXQiOjE2OTQ4NTAwMTksImV4cCI6MjAxMDQyNjAxOX0.KkiYYTJUNTD3K7OkHASV3_ZEv5NIFN-Farw9lT7QIfk


  user:
    build:
      context: ./user-service
    ports:
      - "5100:5100"
    environment: 
      - JWT_SECRET=WmpSVc7vwoUSN/SGtFd1PQO67csTZbX+MmwodyxRnwoJ+fZH750P7WNVYQbK1S7bD+oYikZRGQwvvU2UOj5vzg==
      - SUPABASE_URL=https://iwxacjmydxiforzrvurs.supabase.co
      - SUPABASE_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml3eGFjam15ZHhpZm9yenJ2dXJzIiwicm9sZSI6ImFub24iLCJpYXQiOjE2OTQ4NTAwMTksImV4cCI6MjAxMDQyNjAxOX0.KkiYYTJUNTD3K7OkHASV3_ZEv5NIFN-Farw9lT7QIfk


  matching:
    build:
      context: ./matching-service
    ports:
      - "8080:8080"
    environment:
      - CLIENT_URL=http://34.121.234.55:3000
      - QUESTIONS_API_URL=http://34.121.234.55:8888/questions

  collaboration:
    build:
      context: ./collaboration-service
    ports:
      - "8081:8081"
    environment:
      - CLIENT_URL=http://34.121.234.55:3000
