version: "3.9"

services:
  client:
    build:
      context: ./client
    ports:
      - "3000:3000"
    environment:
      - QUESTIONS_API_URL=http://question:8888/questions
      - USER_API_URL=http://user:5000/user
    depends_on:
      - question
      - user
      - matching
      - collaboration

  question:
    build:
      context: ./question-service
    ports:
      - "8888:8888"
    environment:
      - MONGODB_URL=mongodb://mongo
      - CLIENT_URL=http://localhost:3000
      - MATCHING_URL=http://localhost:8080
    depends_on:
      - mongo

  user:
    build:
      context: ./user-service
    ports:
      - "5000:5000"

  mongo:
    image: mongo:6
    ports:
      - 27017:27017

  matching:
    build:
      context: ./matching-service
    ports:
      - "8080:8080"
    environment:
      - CLIENT_URL=http://localhost:3000
      - QUESTIONS_API_URL=http://question:8888/questions

  collaboration:
    build:
      context: ./collaboration-service
    ports:
      - "8081:8081"
    environment:
      - CLIENT_URL=http://localhost:3000
    
