version: "3.9"

services:
  api:
    build: .
    ports:
      - "8888:8888"
    environment:
      - MONGODB_URL=mongodb://mongo
    depends_on:
      - mongo
  mongo:
    image: mongo:6
    ports:
      - 27017:27017
